spring:
  config:
    import: nacos:batch-gateway-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  application:
    name: batch-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.114.4:8848
        namespace: DNAF
      config:
        server-addr: 172.24.114.4:8848
        namespace: DNAF
        group: DEFAULT_GROUP
        # 配置文件格式
        file-extension: yml